import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight,History,Upload,WandSparkles} from 'lucide-react';
import {api,fileUrl} from './api';
import {ErrorNotice} from './components';
import type {Project,SettingsResponse} from './types';
import {getEditSubmission,readEditSubmission,clearEditSubmission} from './editSubmissions';
import './artwork.css';

interface Draft {draft_id:string;fingerprint:string;artifact_kind:string;origin:string}
interface Version {fingerprint:string;current:boolean;origin:string;created_at:string|null}

export default function AssetEditor({project:p,kind,title,disabled,onRefresh}:{project:Project;kind:string;title:string;disabled:boolean;onRefresh:()=>Promise<void>}){
 const slot='katsu.pending-edit.'+p.id+'.'+kind;
 const [instructions,setInstructions]=useState(()=>{try{return JSON.parse(readEditSubmission(sessionStorage,slot)?.body??'{}').instructions??''}catch{return ''}}),[file,setFile]=useState<File|null>(null),[draft,setDraft]=useState<Draft|null>(null),[versions,setVersions]=useState<Version[]>([]),[settings,setSettings]=useState<SettingsResponse|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const ticket=useRef(0),fileInput=useRef<HTMLInputElement>(null);
 const art=p.artifacts[kind],pending=p.artwork_edit?.kind===kind;
 useEffect(()=>{const current=++ticket.current;let stopped=false;setLoading(true);Promise.all([api<Draft|null>(`/projects/${p.id}/artwork/${kind}/draft`),api<Version[]>(`/projects/${p.id}/artwork/${kind}/versions`)]).then(([preview,rows])=>{if(!stopped&&current===ticket.current){setDraft(preview);setVersions(rows)}}).catch(e=>{if(!stopped)setError(e.message)}).finally(()=>{if(!stopped)setLoading(false)});return()=>{stopped=true}},[p.id,kind,p.updated_at]);
 useEffect(()=>{let stopped=false;api<SettingsResponse>('/settings').then(s=>{if(!stopped)setSettings(s)}).catch(e=>{if(!stopped)setError(e.message)});return()=>{stopped=true}},[]);
 async function action(path:string,options:RequestInit={method:'POST'}){setBusy(true);setError('');try{await api(`/projects/${p.id}/artwork/${kind}/${path}`,options);if(['apply','restore','draft/discard'].includes(path))clearEditSubmission(sessionStorage,slot);await onRefresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function generate(){try{const request=getEditSubmission(sessionStorage,slot,JSON.stringify({instructions,base_fingerprint:art.fingerprint}));await action('draft',{method:'POST',headers:{'Idempotency-Key':request.key},body:request.body})}catch(e){setError((e as Error).message)}}
 async function upload(){if(!file)return;setBusy(true);setError('');try{await api(`/projects/${p.id}/artwork/${kind}/draft/upload`,{method:'POST',headers:{'Content-Type':file.type,'X-Base-Fingerprint':art.fingerprint},body:file});setFile(null);if(fileInput.current)fileInput.current.value='';await onRefresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function choose(file:File|undefined){setError('');if(!file){setFile(null);return}if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>12*1024*1024){setError('Choose a PNG, JPEG or WebP image under 12 MB.');setFile(null);return}setFile(file)}
 const blocked=disabled||busy,editBlocked=blocked||!!p.artwork_edit;
 return <section className="artwork-editor" aria-label={title+' editor'}>
  <div className="artwork-heading"><div><h3>{title}</h3><p>{kind==='thumbnail'?'Keep the complete cover and headline.':'The saved narration and word timing will be reused.'}</p></div><span>Preview before saving</span></div>
  {error&&<ErrorNotice message={error}/>}
  <div className="artwork-comparison"><figure><figcaption>Current image</figcaption><img src={fileUrl(p.id,kind)+'?v='+art.fingerprint} alt={'Current '+title.toLowerCase()}/></figure>{draft?<figure><figcaption>Proposed image <span>{draft.origin==='ai'?'AI edit':'Your upload'}</span></figcaption><img src={fileUrl(p.id,draft.artifact_kind)+'?v='+draft.fingerprint} alt={'Preview of '+title.toLowerCase()}/></figure>:<div className="artwork-awaiting" role="status"><WandSparkles size={24}/><p>{pending?'Katsu is preparing your edit.':loading?'Loading saved previews…':'Your preview will appear here.'}</p><span>{pending?'Your current image is still saved.':'Describe a change or upload an image below.'}</span></div>}</div>
  {draft&&<div className="artwork-save"><p>{kind==='thumbnail'?'Saving updates the thumbnail immediately.':'Saving rebuilds the video with this image and your existing recording.'}</p><div className="actions"><button className="primary" disabled={blocked||pending} onClick={()=>action('apply',{method:'POST',body:JSON.stringify({draft_id:draft.draft_id})})}>Use this image <ArrowRight size={17}/></button><button disabled={blocked||pending} onClick={()=>action('draft/discard')}>Discard preview</button></div></div>}
  {pending&&<div className="artwork-pending"><p>{p.status==='running'||p.status==='queued'?'Preparing an AI preview…':'The edit is paused. Continue production above to recover it, or discard it.'}</p>{p.status!=='running'&&p.status!=='queued'&&<button disabled={blocked} onClick={()=>action('draft/discard')}>Discard pending edit</button>}</div>}
  <div className="artwork-methods"><div><label htmlFor={'edit-'+kind}>Describe an AI change</label><textarea id={'edit-'+kind} disabled={editBlocked} maxLength={4000} value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder={kind==='thumbnail'?'Make the headline bigger and tilt it slightly to the left.':'Make the character look surprised; keep the rest of the scene.'}/><p className="field-hint">Uses this image as the reference. Review the result before saving.</p><button disabled={editBlocked||!!draft||instructions.trim().length<3||!settings?.connections.openai} onClick={generate}><WandSparkles size={17}/>{busy?'Working…':'Generate edit preview'}</button><p className="field-hint">{settings?.connections.openai?`About $${settings.settings.image_estimate_usd.toFixed(2)} estimated per edit, within the project spending limit.`:<><Link to="/settings">Connect OpenAI in Settings</Link> to use AI editing.</>}</p></div><div><label htmlFor={'upload-'+kind}>Upload your own image</label><input ref={fileInput} id={'upload-'+kind} type="file" disabled={editBlocked} accept="image/png,image/jpeg,image/webp" onChange={e=>choose(e.target.files?.[0])}/><p className="field-hint">PNG, JPEG or WebP · Under 12 MB · Still images only</p><button disabled={editBlocked||!file} onClick={upload}><Upload size={17}/>Upload preview</button><p className="field-hint">Uploads and video rebuilding use no AI credits.</p></div></div>
  <details className="artwork-history"><summary><History size={16}/>Previous versions ({versions.filter(v=>!v.current).length})</summary>{versions.filter(v=>!v.current).length===0?<p className="muted">New versions appear here after saving.</p>:versions.map((version,i)=><div className="artwork-version" key={version.fingerprint}><div><strong>{version.origin==='original'?'Original image':version.origin==='ai'?'AI edit':'Uploaded image'}</strong><span>{version.current?'Current image':version.created_at?new Date(version.created_at).toLocaleString():`Saved version ${versions.length-i}`}</span></div>{!version.current&&<button disabled={editBlocked} onClick={()=>action('restore',{method:'POST',body:JSON.stringify({fingerprint:version.fingerprint})})}>Restore version</button>}</div>)}</details>
 </section>
}
