// Real local browser acceptance. No provider network requests are made.
const {chromium} = require(process.env.KATSU_PLAYWRIGHT_PATH || 'playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');

(async()=>{
 const out=path.resolve(__dirname,'../evidence');fs.mkdirSync(out,{recursive:true});
 const browser=await chromium.launch({headless:true,channel:'chrome'});
 const page=await browser.newPage({viewport:{width:1360,height:960}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const base='http://127.0.0.1:8850';
 await page.goto(base);await page.getByRole('heading',{name:/My videos/}).waitFor();
 await page.getByRole('button',{name:'Bring in our first video'}).click();
 await page.waitForURL('**/projects/*');
 await page.getByRole('heading',{name:'Why Are Humans Never Satisfied?'}).waitFor();
 const importedURL=page.url();
 await page.locator('video').evaluate(v=>new Promise((resolve,reject)=>{if(v.readyState>=1)return resolve(v.duration);v.addEventListener('loadedmetadata',()=>resolve(v.duration),{once:true});v.addEventListener('error',()=>reject(new Error('Playback failed')),{once:true})})).then(d=>assert(d>568&&d<569));
 await page.locator('video').evaluate(async v=>{v.muted=true;await v.play()});
 await page.waitForFunction(()=>document.querySelector('video').currentTime>0.1);
 await page.locator('video').evaluate(v=>v.pause());
 await page.screenshot({path:path.join(out,'episode-desktop.png'),fullPage:true});
 await page.getByRole('tab',{name:'Images (120)'}).click();
 assert.equal(await page.locator('.scene-card').count(),120);
 assert((await page.locator('.scene-wording').first().textContent()).includes('You finally get the thing'));
 await page.locator('.scene-gallery').scrollIntoViewIfNeeded();
 await page.waitForFunction(()=>Array.from(document.querySelectorAll('.scene-card img')).slice(0,3).every(i=>i.complete&&i.naturalWidth>0));
 await page.screenshot({path:path.join(out,'gallery-desktop.png')});
 await page.getByRole('link',{name:'Settings',exact:true}).click();
 await page.getByRole('heading',{name:'Make it yours.'}).waitFor();
 assert.equal(await page.locator('input[type=password]').count(),2);
 await page.getByLabel('Target minutes').fill('8');
 await page.getByRole('button',{name:'Save preferences'}).click();
 await page.getByRole('status').filter({hasText:'Studio preferences saved.'}).waitFor();
 await page.reload();assert.equal(await page.getByLabel('Target minutes').inputValue(),'8');
 await page.getByRole('button',{name:'Check connections'}).click();
 await page.getByText('Add your API key.',{exact:false}).first().waitFor();
 await page.screenshot({path:path.join(out,'settings-desktop.png'),fullPage:true});
 await page.getByRole('link',{name:'New video',exact:true}).click();
 await page.getByLabel('Video topic',{exact:true}).fill('Browser acceptance test — missing credentials');
 assert.equal(await page.getByLabel('Illustrations',{exact:true}).count(),0);
 await page.screenshot({path:path.join(out,'create-desktop.png'),fullPage:true});
 await page.getByRole('button',{name:'Make my video',exact:false}).click();
 await page.getByText('Let’s get this moving again.').waitFor();
 assert((await page.locator('.attention').textContent()).includes('Open Settings'));
 const stoppedId=page.url().split('/').pop();
 const job=await page.request.get(`${base}/api/projects/${stoppedId}`).then(r=>r.json());
 assert.equal(job.status,'needs_attention');assert.equal(job.estimated_committed_usd,0);
 await page.getByRole('button',{name:'Continue production',exact:false}).click();
 await page.getByText('Let’s get this moving again.').waitFor();
 await page.getByRole('link',{name:'My videos',exact:true}).first().click();
 await page.screenshot({path:path.join(out,'studio-desktop.png'),fullPage:true});
 const desktopOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert(!desktopOverflow);
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.join(out,'studio-mobile.png'),fullPage:true});
 assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)));
 await page.goto(importedURL);await page.locator('video').waitFor();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.join(out,'episode-mobile.png'),fullPage:true});
 assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)));
 await page.getByRole('tab',{name:'Images (120)'}).click();
 await page.locator('.scene-gallery').scrollIntoViewIfNeeded();
 await page.waitForFunction(()=>document.querySelector('.scene-card img')?.complete);
 await page.screenshot({path:path.join(out,'gallery-mobile.png')});
 await page.getByRole('link',{name:'Settings',exact:true}).click();
 await page.getByRole('heading',{name:'Make it yours.'}).waitFor();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.join(out,'settings-mobile.png'),fullPage:true});
 assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)));
 await page.getByRole('link',{name:'New video',exact:true}).click();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.join(out,'create-mobile.png'),fullPage:true});
 assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)));
 assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(out,'browser-verification.json'),JSON.stringify({passed:true,importedURL,missingKeyProject:stoppedId,scenes:120,desktop:[1360,960],mobile:[390,844],playback:true,settingsPersistence:true,missingKeyRecovery:true,overflow:false,pageErrors:errors},null,2));
 console.log('Browser acceptance passed: import, playback, gallery, settings, creation, resume, desktop/mobile, no page errors.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
