import {useEffect,useRef,useState} from 'react';
import {Link,useLocation,useNavigate} from 'react-router-dom';
import {ArrowLeft,ArrowRight,Sparkles} from 'lucide-react';
import type {SettingsResponse,Project} from '../types';
import {api} from '../api';
import {ErrorNotice,Loading} from '../components';
import TopicSuggestions from '../TopicSuggestions';

const pendingKey='katsu.pending-project';
type Pending={key:string;body:string};
function readPending():Pending|null{try{const raw=sessionStorage.getItem(pendingKey);if(!raw)return null;const saved=JSON.parse(raw);const data=JSON.parse(saved.body);return typeof saved.key==='string'&&typeof data.topic==='string'&&Number.isFinite(data.target_seconds)&&Number.isFinite(data.scene_count)?saved:null}catch{return null}}

export default function Create(){
 const location=useLocation(),navigate=useNavigate();
 const [pending]=useState(readPending);
 const draft=pending?JSON.parse(pending.body):null;
 const [topic,setTopic]=useState(location.state?.topic??draft?.topic??''),[settings,setSettings]=useState<SettingsResponse|null>(null),[minutes,setMinutes]=useState(draft?draft.target_seconds/60:8),[scenes,setScenes]=useState(draft?.scene_count??72),[budget,setBudget]=useState(draft?.budget_usd??20),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const key=useRef(pending?.key??crypto.randomUUID()),submitted=useRef(false);
 const previousBody=useRef(pending?.body??'');
 const topicField=useRef<HTMLTextAreaElement>(null);
 function selectTopic(value:string){setTopic(value);key.current=crypto.randomUUID();topicField.current?.focus()}
 useEffect(()=>{api<SettingsResponse>('/settings').then(s=>{setSettings(s);if(!pending){setMinutes(s.settings.target_seconds/60);setScenes(s.settings.scene_count);setBudget(s.settings.budget_usd)}}).catch(e=>setError(e.message))},[]);
 async function create(e:React.FormEvent){e.preventDefault();if(submitted.current)return;submitted.current=true;setBusy(true);setError('');const body=JSON.stringify({topic,target_seconds:Math.round(minutes*60),scene_count:scenes,budget_usd:budget});if(previousBody.current&&previousBody.current!==body)key.current=crypto.randomUUID();previousBody.current=body;try{sessionStorage.setItem(pendingKey,JSON.stringify({key:key.current,body}));const p=await api<Project>('/projects',{method:'POST',headers:{'Idempotency-Key':key.current},body});sessionStorage.removeItem(pendingKey);navigate('/projects/'+p.id)}catch(e){setError((e as Error).message);submitted.current=false;setBusy(false)}}
 return <div className="create-layout"><section><Link className="back-link" to="/"><ArrowLeft size={16}/>My videos</Link><h1>What’s the question?</h1><p className="lead">Give Katsu a topic. Get a complete illustrated explainer.</p>{error&&<ErrorNotice message={error}/>}<form onSubmit={create}><label htmlFor="topic">Video topic</label><textarea id="topic" ref={topicField} className="topic-input" autoFocus placeholder="Why are humans never satisfied?" minLength={3} maxLength={300} required value={topic} onChange={e=>{setTopic(e.target.value);key.current=crypto.randomUUID()}}/><span className="field-hint">A question, a strange idea, or something you can’t stop thinking about.</span><TopicSuggestions topic={topic} onSelect={selectTopic} disabled={busy}/><div className="form-row"><div><label htmlFor="minutes">Target length</label><div className="unit-input"><input id="minutes" type="number" min={1} max={30} step={1} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/><span>minutes</span></div></div><div><label htmlFor="scenes">Illustrations</label><input id="scenes" type="number" min={4} max={120} value={scenes} onChange={e=>setScenes(Number(e.target.value))}/></div></div><details><summary>Spending limit</summary><label htmlFor="budget">Estimated project limit (USD)</label><input id="budget" type="number" min={.1} max={500} step={.1} value={budget} onChange={e=>setBudget(Number(e.target.value))}/><p className="field-hint">The studio reserves estimates before requests. Provider billing may differ.</p></details><button className="primary wide" disabled={busy||!settings} type="submit">{busy?'Starting your video…':'Make my video'} <ArrowRight size={19}/></button></form>{!settings&&!error&&<Loading/>}{settings&&(!settings.connections.openai||!settings.connections.elevenlabs||!settings.settings.voice_id)&&<p className="setup-warning">You can save your idea now. <Link to="/settings">Connect your accounts and choose a voice</Link> before production.</p>}</section><aside className="recipe"><Sparkles size={28}/><h2>From “what if”<br/>to “watch this.”</h2><ol><li><strong>A story worth telling</strong><p>Research, a full English script, and a scene plan.</p></li><li><strong>The Katsu look</strong><p>Original still illustrations with your saved character style.</p></li><li><strong>Your voice, in time</strong><p>Narration, shorter pauses, and images matched to the words.</p></li><li><strong>A finished episode</strong><p>A checked 1080p video and its thumbnail, ready to download.</p></li></ol><p className="recipe-foot">Actual length follows the recording. Eight minutes is a target.</p></aside></div>
}
