import {useEffect,useRef,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {ArrowLeft,Download,RefreshCw,Square,ArrowRight,Copy,ExternalLink,Pencil,Check} from 'lucide-react';
import {api,fileUrl,runtime} from '../api';
import type {Project,Scene,Script,RequestRecord} from '../types';
import {ErrorNotice,Loading,Progress} from '../components';
import AssetEditor from '../AssetEditor';

type Tab='video'|'narration'|'images'|'thumbnail'|'sources';
const tabs:Tab[]=['video','narration','images','thumbnail','sources'];
export default function ProjectPage(){
 const {id}=useParams();
 const [project,setProject]=useState<Project|null>(null),[scenes,setScenes]=useState<Scene[]>([]),[script,setScript]=useState<Script|null>(null),[requests,setRequests]=useState<RequestRecord[]>([]),[tab,setTab]=useState<Tab>('video'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false),[billingChecked,setBillingChecked]=useState(false);
 const generation=useRef(0),flight=useRef<Promise<void>|null>(null);
 async function load(fresh=false){if(fresh){generation.current++;flight.current=null}if(flight.current)return flight.current;const ticket=generation.current;const task=(async()=>{const p=await api<Project>('/projects/'+id);const [rows,records]=await Promise.all([api<Scene[]>(`/projects/${id}/scenes`),api<RequestRecord[]>(`/projects/${id}/requests`)]);let narration:Script|null=null;if(p.artifacts.script){const r=await fetch(fileUrl(id!,'script'));if(r.ok)narration=await r.json()}if(ticket===generation.current){setProject(p);setScenes(rows);setRequests(records);setScript(narration)}})();flight.current=task;try{await task}finally{if(ticket===generation.current)flight.current=null}}
 useEffect(()=>{generation.current++;flight.current=null;setProject(null);setScenes([]);setScript(null);setRequests([]);setError('');let stopped=false;const poll=()=>{if(!stopped)load().catch(e=>{if(!stopped)setError(e.message)})};poll();const timer=setInterval(poll,2500);return()=>{stopped=true;generation.current++;clearInterval(timer)}},[id]);
 async function action(path:string){setBusy(true);setError('');try{await api(`/projects/${id}/${path}`,{method:'POST'});await load(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function acknowledge(){setBusy(true);try{await api(`/projects/${id}/acknowledge-unknown`,{method:'POST'});setBillingChecked(false);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function downloadPackage(){setBusy(true);setError('');try{await api(`/projects/${id}/package-images`,{method:'POST'});await load(true);window.location.assign(fileUrl(id!,'images_package',true))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!project)return error?<ErrorNotice message={error}/>:<Loading/>;
 const active=project.status==='running'||project.status==='queued',hasVideo=!!project.artifacts.video,unknown=requests.some(r=>r.state==='unknown'||r.state==='reserved');
 return <><Link className="back-link" to="/"><ArrowLeft size={16}/>My videos</Link><div className="project-heading"><div><h1>{project.title}</h1><p>{project.imported?'Our first episode · ':''}{runtime(project.actual_seconds)} · {project.total_assets>0?`${project.total_assets} illustrations`:'Illustrations planned after the script'} · English</p></div><div className="actions">{hasVideo&&<a className="primary" href={fileUrl(project.id,'video',true)}><Download size={18}/>Download video</a>}{active?<button disabled={busy||project.cancel_requested} onClick={()=>action('cancel')}><Square size={15}/>{project.cancel_requested?'Stopping…':'Stop production'}</button>:(!hasVideo||project.status!=='completed')&&<button className="primary" disabled={busy||unknown} onClick={()=>action('resume?apply_settings=true')}>Continue production <ArrowRight size={17}/></button>}</div></div>{error&&<ErrorNotice message={error}/>}<Progress project={project}/>{project.error&&<div className="attention"><strong>Let’s get this moving again.</strong><p>{project.error}</p><Link to="/settings">Open Settings <ArrowRight size={15}/></Link></div>}{unknown&&!active&&<div className="paid-attention"><h3>A paid request has an uncertain outcome.</h3><p>Check the saved request details and your provider’s billing first. Successful results may already exist. Allowing another attempt can incur an additional charge; earlier estimates remain counted.</p><label className="checkbox"><input type="checkbox" checked={billingChecked} onChange={e=>setBillingChecked(e.target.checked)}/>I checked the outcome and want to allow another paid attempt.</label><button disabled={!billingChecked||busy} onClick={acknowledge}>Allow another attempt</button></div>}<div className="tabs" role="tablist" aria-label="Episode content">{tabs.map(t=><button id={'tab-'+t} role="tab" tabIndex={tab===t?0:-1} onKeyDown={e=>{const order=tabs;let index=order.indexOf(t);if(e.key==='ArrowRight')index=(index+1)%order.length;else if(e.key==='ArrowLeft')index=(index+order.length-1)%order.length;else if(e.key==='Home')index=0;else if(e.key==='End')index=order.length-1;else return;e.preventDefault();setTab(order[index]);document.getElementById('tab-'+order[index])?.focus()}} aria-selected={tab===t} aria-controls={'panel-'+t} key={t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t==='images'?`Images (${scenes.length})`:t[0].toUpperCase()+t.slice(1)}</button>)}</div><section id={'panel-'+tab} role="tabpanel" aria-labelledby={'tab-'+tab} className="tab-content">
 {tab==='video'&&<>{project.render_only&&<p className="saved-export-note">Your previous export remains available while the updated video is built.</p>}{hasVideo?<div className="player-wrap"><video key={project.artifacts.video.fingerprint} controls preload="metadata" poster={project.artifacts.thumbnail?fileUrl(project.id,'thumbnail')+'?v='+project.artifacts.thumbnail.fingerprint:project.artifacts.scene_1?fileUrl(project.id,'scene_1'):undefined} src={fileUrl(project.id,'video')}/><div className="player-caption"><span>1080p · 30 fps · Still illustrations</span><a href={fileUrl(project.id,'verification',true)}>View export checks <ExternalLink size={14}/></a></div></div>:<div className="waiting-video"><img src="/api/brand/avatar" alt=""/><h2>{active?'Katsu is putting it together.':'Your video will live here.'}</h2><p>{active?'Follow the stages above. Your script and illustrations appear as they’re ready.':'Complete setup or continue production to create your export.'}</p></div>}<div className="project-facts"><div><span>Target length</span><strong>{Math.round(project.settings.target_seconds/60)} minutes</strong></div><div><span>Recorded length</span><strong>{runtime(project.actual_seconds)}</strong></div><div><span>Committed estimates</span><strong>${project.estimated_committed_usd.toFixed(2)} <small>/ ${project.settings.budget_usd.toFixed(2)}</small></strong></div><div><span>Voice</span><strong>{project.settings.voice_name||(project.imported?'Hannibal · original recording':'Selected in Settings')}</strong></div></div><p className="muted">Recorded length sets the final runtime. Spending figures are estimates, separate from provider billing.</p>{hasVideo&&<div className="export-downloads">{project.artifacts.thumbnail&&<a href={fileUrl(project.id,'thumbnail',true)}>Download thumbnail</a>}<a href={fileUrl(project.id,'script',true)}>Download script data</a><a href={fileUrl(project.id,'timeline',true)}>Download timing report</a>{project.artifacts.narration_text&&<a href={fileUrl(project.id,'narration_text',true)}>Download narration text</a>}<button className="text-button" disabled={busy||active} onClick={downloadPackage}><Download size={16}/>Download images & scene wording</button></div>}{!active&&project.artifacts.scenes&&<button className="text-button" disabled={busy} onClick={()=>action('render')}><RefreshCw size={16}/>Build export again from saved assets</button>}</>}
 {tab==='narration'&&<>{script?<><div className="section-heading"><h2>The complete voiceover</h2><button className="text-button" onClick={async()=>{try{await navigator.clipboard.writeText(script.narration);setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{setError('Copy is unavailable. Select the narration below and copy it.')}}}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Copied':'Copy narration'}</button></div>{project.artifacts.audio&&<audio controls preload="metadata" src={fileUrl(project.id,'audio')}/>}<div className="narration-text">{script.narration.split('\n\n').map((text,i)=><p key={i}>{text}</p>)}</div><p className="muted">To change a line, open its scene under Images. Changes to words require a new recording.</p></>:<p>The narration will appear after the writing stage.</p>}</>}
 {tab==='images'&&<><p className="scene-explanation">Every illustration has its exact voiceover below it. Edit an image or upload a replacement; saving rebuilds the video with your existing recording.</p><div className="scene-gallery">{scenes.map(s=><SceneCard key={s.id} scene={s} project={project} disabled={active||busy||unknown} onRefresh={()=>load(true)} onError={setError}/>)}</div>{scenes.length===0&&<p>The scene plan will appear here when it’s ready.</p>}</>}
 {tab==='thumbnail'&&<ThumbnailPanel project={project} active={active} disabled={busy||active||unknown||!hasVideo} onRefresh={()=>load(true)} onGenerate={()=>action('thumbnail'+(project.artifacts.thumbnail?'?regenerate=true':''))}/>}
 {tab==='sources'&&<>{script?.sources.length?<div className="sources">{script.sources.map((s,i)=><article key={s.url}><span className="source-number">{i+1}</span><div><h3><a href={s.url} target="_blank" rel="noreferrer">{s.title} <ExternalLink size={15}/></a></h3><p>{s.evidence}</p></div></article>)}</div>:<p>{project.imported?'This historical import preserves the existing production files. It has no automatic research record.':'The research references will appear after the first stage.'}</p>}<details className="request-details"><summary>Request and spending records ({requests.length})</summary>{requests.map(r=><div className="request-row" key={r.key}><code>{r.key.split(':')[1]}</code><span>{r.state}</span><span>${r.estimated_usd.toFixed(3)} estimated</span></div>)}</details></>}
 </section></>
}

function SceneCard({scene:s,project:p,disabled,onRefresh,onError}:{scene:Scene;project:Project;disabled:boolean;onRefresh:()=>Promise<void>;onError:(v:string)=>void}){
 const [imageEditing,setImageEditing]=useState(false),[editing,setEditing]=useState(false),[wording,setWording]=useState(s.voiceover),[visual,setVisual]=useState(s.visual),[saving,setSaving]=useState(false);
 async function save(){setSaving(true);try{await api(`/projects/${p.id}/scenes/${s.id}`,{method:'PATCH',body:JSON.stringify({voiceover:wording,visual})});setEditing(false);await onRefresh()}catch(e){onError((e as Error).message)}finally{setSaving(false)}}
 async function regenerate(){setSaving(true);try{await api(`/projects/${p.id}/scenes/${s.id}/regenerate`,{method:'POST'});await onRefresh()}catch(e){onError((e as Error).message)}finally{setSaving(false)}}
 const art=p.artifacts['scene_'+s.id];
 return <article className={"scene-card"+(imageEditing?" artwork-open":"")}><div className="scene-image">{art?<img key={art.fingerprint} src={fileUrl(p.id,'scene_'+s.id)+'?v='+art.fingerprint} alt={s.visual} loading="lazy"/>:<span>Illustration pending</span>}<span className="scene-number">Scene {String(s.id).padStart(2,'0')}</span></div>{editing?<div className="scene-editor"><label htmlFor={'word-'+s.id}>Exact voiceover</label><textarea id={'word-'+s.id} value={wording} onChange={e=>setWording(e.target.value)}/><label htmlFor={'visual-'+s.id}>What should this image show?</label><textarea id={'visual-'+s.id} value={visual} onChange={e=>setVisual(e.target.value)}/><p className="field-hint">Changing words creates new narration. Changing the visual updates this image.</p><div className="actions"><button className="primary" disabled={saving||disabled||!wording.trim()||!visual.trim()} onClick={save}>Save changes</button><button disabled={saving} onClick={()=>setEditing(false)}>Cancel</button></div></div>:<><p className="scene-wording">{s.voiceover}</p><div className="scene-actions"><button className="text-button" disabled={disabled||saving} onClick={()=>{setWording(s.voiceover);setVisual(s.visual);setEditing(true)}}><Pencil size={14}/>Edit words & visual</button><button className="text-button" disabled={disabled||saving||!art} onClick={()=>setImageEditing(!imageEditing)}><Pencil size={14}/>{imageEditing?'Close image editor':'Edit image'}</button><button className="text-button" disabled={disabled||saving} onClick={regenerate}><RefreshCw size={14}/>{saving?'Starting…':'New image'}</button></div></>}{imageEditing&&art&&<AssetEditor project={p} kind={'scene_'+s.id} title={'Edit scene '+s.id+' image'} disabled={disabled} onRefresh={onRefresh}/>}</article>
}


function ThumbnailPanel({project:p,active,disabled,onGenerate,onRefresh}:{project:Project;active:boolean;disabled:boolean;onGenerate:()=>void;onRefresh:()=>Promise<void>}){
 const [editing,setEditing]=useState(false);
 const thumb=p.artifacts.thumbnail;
 const headline=thumb?String(thumb.metadata.headline??''):'';
 return <div className="thumbnail-layout"><div>{thumb?<><img className="thumbnail-preview" src={fileUrl(p.id,'thumbnail')+'?v='+thumb.fingerprint} alt={'Episode thumbnail: '+headline}/><p className="thumbnail-caption">3840 × 2160 · JPEG · Under 2 MB</p></>:<div className="thumbnail-placeholder"><img src="/api/brand/avatar" alt=""/><h2>{active?'One last first impression.':'Your episode needs a cover.'}</h2><p>{active?'A thumbnail is created automatically after the video export.':'Create a thumbnail for this finished episode.'}</p></div>}</div><div className="thumbnail-details"><h2>The first impression.</h2><p>A short, clear headline and expressive Katsu artwork, based on the finished story.</p>{headline&&<p className="thumbnail-headline">“{headline}”</p>}{thumb?.metadata.source==='codex_artwork'&&<p className="muted">This first thumbnail uses artwork created in our session. Future thumbnails use your connected account.</p>}<div className="thumbnail-actions">{thumb&&<a className="primary" href={fileUrl(p.id,'thumbnail',true)}><Download size={17}/>Download thumbnail</a>}<button disabled={disabled||!thumb} onClick={()=>setEditing(!editing)}><Pencil size={16}/>{editing?'Close editor':'Edit thumbnail'}</button><button disabled={disabled} onClick={onGenerate}><RefreshCw size={16}/>{thumb?'New thumbnail':'Make thumbnail'}</button></div><p className="field-hint">Generation uses your OpenAI account and the project’s spending limit. Your saved video and recording stay reusable.</p>{!p.artifacts.video&&<p className="field-hint">Finish the video first; its thumbnail follows automatically.</p>}</div>{editing&&thumb&&<div className="thumbnail-editor"><AssetEditor project={p} kind="thumbnail" title="Edit thumbnail" disabled={disabled} onRefresh={onRefresh}/></div>}</div>
}
