import {useEffect,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {ArrowRight,Plus,Play,Import} from 'lucide-react';
import {api,fileUrl,runtime,statusName} from '../api';
import type {Project,SettingsResponse} from '../types';
import {ErrorNotice,Loading} from '../components';

export default function Projects(){
 const [projects,setProjects]=useState<Project[]|null>(null),[setup,setSetup]=useState<SettingsResponse|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[topic,setTopic]=useState('');
 const navigate=useNavigate();
 useEffect(()=>{let alive=true;const load=()=>Promise.all([api<Project[]>('/projects'),api<SettingsResponse>('/settings')]).then(([p,s])=>{if(alive){setProjects(p);setSetup(s)}}).catch(e=>{if(alive)setError(e.message)});load();const timer=setInterval(load,4000);return()=>{alive=false;clearInterval(timer)}},[]);
 async function importVideo(){setBusy(true);setError('');try{const p=await api<Project>('/import-existing',{method:'POST'});navigate('/projects/'+p.id)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const connected=setup?.connections.openai&&setup?.connections.elevenlabs&&setup.settings.voice_id;
 return <><section className="intro"><div><h1>Your next idea,<br/><span className="marker">made into a video.</span></h1><p>Curious questions. Original illustrations. Your voice.<br className="desktop-break"/> All in one little studio.</p></div><img className="intro-character" src="/api/brand/avatar" alt="Katsu holding his magic wand"/></section><form className="topic-bar" onSubmit={e=>{e.preventDefault();navigate('/new',{state:{topic}})}}><label className="sr-only" htmlFor="quick-topic">Your next video topic</label><input id="quick-topic" value={topic} onChange={e=>setTopic(e.target.value)} placeholder="What should we explain next?" maxLength={300}/><button className="primary" type="submit">Create a video <ArrowRight size={18}/></button></form>{setup&&!connected&&<div className="setup-strip"><span>Connect your image and voice accounts once. Then just bring an idea.</span><Link to="/settings">Set up the studio <ArrowRight size={16}/></Link></div>}{error&&<ErrorNotice message={error}/>}<div className="section-heading"><h2>My videos <span>{projects?.length??0}</span></h2><button className="text-button" disabled={busy} onClick={importVideo}><Import size={17}/>{busy?'Bringing it in…':'Bring in our first video'}</button></div>{!projects?<Loading/>:projects.length===0?<div className="empty-state"><ClapperEmpty/><h3>Your first episode starts here.</h3><p>Enter a topic above, or bring in the video we already made.</p></div>:<div className="video-list">{projects.map(p=><Link key={p.id} to={'/projects/'+p.id} className="episode"><div className="episode-art">{(p.artifacts.thumbnail||p.artifacts.scene_1)?<img key={(p.artifacts.thumbnail||p.artifacts.scene_1).fingerprint} src={fileUrl(p.id,p.artifacts.thumbnail?'thumbnail':'scene_1')+'?v='+(p.artifacts.thumbnail||p.artifacts.scene_1).fingerprint} alt=""/>:<span className="pending-art"><span>KATSU</span>Making something curious.</span>}<span className="play-mark"><Play size={20} fill="currentColor"/></span>{p.actual_seconds!==null&&<span className="runtime">{runtime(p.actual_seconds)}</span>}</div><div className="episode-info"><div className="episode-meta"><span className={'status '+p.status}>{statusName(p.status)}</span><span>{new Date(p.created_at).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</span></div><h3>{p.title}</h3><p>{p.imported?'Our original episode':`${p.settings.scene_count} scenes planned`}{p.actual_seconds!==null?` · ${runtime(p.actual_seconds)} recorded`:` · ${Math.round(p.settings.target_seconds/60)} min target`}</p><span className="episode-link">{p.status==='completed'?'Open episode':'Follow production'} <ArrowRight size={17}/></span></div></Link>)}</div>}<div className="studio-note"><p>Keep the curiosity. Let the studio handle the production.</p><Link to="/new"><Plus size={17}/>Start another idea</Link></div></>
}
function ClapperEmpty(){return <div className="empty-ink" aria-hidden="true"><Play size={34}/></div>}
